# Workflow to check branch naming convention

name: CI - Branch Naming
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  branch-naming-rules:
    runs-on: ubuntu-18.04
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/PE\d-(\d)+-([a-z])+' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'feature,bugfix,hotfix,release' # All branches should start with the given prefix
          ignore: master,develop # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 35 # Max length of the branch name
