# Workflow to analyze Flutter app

name: CI - Flutter Analyze

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  flutter-analyze:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v1
        with:
          channel: "beta"

      - name: Get Dependencies
        run: flutter pub get

      - name: Check Code Format
        run: flutter format --set-exit-if-changed .

      - name: Analyze for Errors
        run: flutter analyze .
