# Notify the engineering team if this pull request is labeled urgent
name: MS - Urgent Notify

on:
  pull_request:
    types: [ "labeled" ]

jobs:
  notify_slack:
    if: ${{ github.event.label.name == 'urgent' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Notify Engineering Slack Channel
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: "Happy Poly Team Robot"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Urgent: ${{ github.event.pull_request.title }}"
          SLACK_ICON: "https://avatars.githubusercontent.com/u/83420744?v=4"
          SLACK_CHANNEL: "engineering"
          SLACK_COLOR: "#ff0000"
          MSG_MINIMAL: ref,actions url
          SLACK_MESSAGE: |
            @${{ github.actor }} marked pull request **${{ github.event.pull_request.title }}** as urgent.
            Pull request number: ${{ github.event.pull_request.number }}.
            See pull request: ${{ github.event.pull_request.html_url }}.
            Check differences (raw): ${{ github.event.pull_request.diff_url }}.
            Pull request state: ${{ github.event.pull_request.state }}.

            _If possible, please review this pull request as soon as possible. Thank you for your attention and have a great day!_
